{"version":3,"sources":["../../app-src/util/ApplicationException.js"],"names":["ApplicationException","Error","constructor","msg","name","exception","isApplicationException","err","Object","getPrototypeOf","getExceptionMessage","message","console","log"],"mappings":";;;;;;AAAO,kBAAMA,oBAAN,SAAmCC,KAAnC,CAAyC;;AAE5CC,4BAAYC,MAAM,EAAlB,EAAsB;AAClB,0BAAMA,GAAN;AACA,yBAAKC,IAAL,GAAY,KAAKF,WAAL,CAAiBE,IAA7B;AACH;AAL2C;;;;AAQhD,kBAAMC,YAAYL,oBAAlB;;AAEO,qBAASM,sBAAT,CAAgCC,GAAhC,EAAqC;AACxC,uBAAOA,eAAeF,SAAf,IAA4BG,OAAOC,cAAP,CAAsBF,GAAtB,aAAsCF,SAAzE;AACH;;;;AAEM,qBAASK,mBAAT,CAA6BH,GAA7B,EAAkC;AACrC,oBAAGD,uBAAuBC,GAAvB,CAAH,EAAgC;AAC5B,2BAAOA,IAAII,OAAX;AACH;;AAEDC,wBAAQC,GAAR,CAAYN,GAAZ;AACA,uBAAO,sCAAP;AACH","file":"ApplicationException.js","sourcesContent":["export class ApplicationException extends Error {\n\n    constructor(msg = '') {\n        super(msg);\n        this.name = this.constructor.name;\n    }\n}\n\nconst exception = ApplicationException;\n\nexport function isApplicationException(err) {\n    return err instanceof exception || Object.getPrototypeOf(err) instanceof exception\n}\n\nexport function getExceptionMessage(err) {\n    if(isApplicationException(err)) {\n        return err.message;\n    } \n\n    console.log(err);\n    return 'Não foi possível realizar a operação';\n}"]}